config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :details do 
  	member do 
  		get 'layout3'
  		get 'layout1'
      get 'showprint' 		
  	end
  end
  root "details#index"

  devise_for :users, :controllers => { registrations: 'registrations' }
end

app/models/detail.rb
class Detail < ApplicationRecord
	belongs_to :user
	is_impressionable
	validates :layout, numericality: { less_than_or_equal_to: 6,  only_integer: true }

	has_attached_file :image, styles: { medium: "109x109#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	
	msg = "There are many variations of passages of Lorem Ipsum available. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc."
	oneparagraph = "There are many variations of passages of Lorem Ipsum available. If you are going to use a passage of Lorem Ipsum"
	skills_word = "skill 1"
	workplace = 'Galactic zoo'
	workplace_subheader = 'playing football with lions and dancing with dinosaurs'
	date = '2100 -2160'

	after_initialize do
	    if new_record?
	      self.header ||= 'Onipe Theoderic' # be VERY careful with ||= and False values
	      self.subheader ||= 'the best website developer in the world'
	      self.email ||= 'onipetheoderic@gmail.com'
	      self.telephone ||= '07039148866'
	      self.sex ||= 'Male'
	      self.address ||= 'no 12 police road, ilorin'
	      self.githublink ||= 'githublink/theoderic'
	      self.twitter ||= 'twitter/theoderic'
	      self.facebook ||= 'facebook/theoderic'
	      self.objectives ||= msg
	      self.experience ||= msg
	      self.experience2 ||= msg
	      self.experience3 ||= msg
	      self.experience4 ||= msg
	      self.experience5 ||= msg
	      self.experience6 ||= msg
	      self.experience7 ||= msg

	      self.language ||= 'English, French, Mandarian, Greek, Latin, Ebira'
	      self.interest ||= 'meeting new people, making friends'
	      
	      self.education ||= msg
	      self.education2 ||= msg
	      self.education3 ||= msg
	      self.education4 ||= msg
	      self.education5 ||= workplace_subheader
	      self.education6 ||= workplace_subheader
	      self.education7 ||= workplace_subheader

	      self.hobby ||= 'swimming, dancing, running, reading, gaming, cooking'
	      self.referee ||= oneparagraph
	      self.project ||= oneparagraph

	      self.skill01 ||= skills_word
	      self.skill02 ||= skills_word
	      self.skill03 ||= skills_word
	      self.skill04 ||= skills_word
	      self.skill05 ||= skills_word
	      self.skill06 ||= skills_word
	      self.skill07 ||= skills_word
	      self.skill08 ||= skills_word

	      self.label1 ||= 'Profile'
	      self.label2 ||= 'Skills'
	      self.label3 ||= 'Technical'
	      self.label4 ||= 'Experience'
	      self.label5 ||= 'referees'
	      self.label6 ||= 'hobbies'
	      self.label7 ||= 'Education'
	      self.label8 ||= 'Self Appraisal'

	      self.techskill1 ||= 'techskill1'
	      self.techskill2 ||= 'techskill2'
	      self.techskill3 ||= 'techskill3'
	      self.techskill4 ||= 'techskill4'
	      self.techskill5 ||= 'techskill5'
	      self.techskill6 ||= 'techskill6'
	      self.techskill7 ||= 'techskill7'
	      self.techskill8 ||= 'techskill8'
	      self.techskill9 ||= 'techskill9'
	      self.techskill10 ||= 'techskill10'
	      self.techskill11 ||= 'techskill11'
	      self.techskill12 ||= 'techskill12'
	      self.techskill13 ||= 'techskill13'
	      self.techskill14 ||= 'techskill14'
	      self.techskill15 ||= 'techskill15'
	      self.techskill16 ||= 'techskill16'
	      self.techskill17 ||= 'techskill17'
	      self.techskill18 ||= 'techskill18'
	      self.techskill19 ||= 13
	      self.techskill20 ||= 'techskill20'
	      self.techskill21 ||= 12
	      self.techskill22 ||= 12
	      self.techskill23 ||= 14
	      self.techskill24 ||= 13
	      self.techskill25 ||= 13
	      self.techskill26 ||= 12

	      self.expdate1 ||= date
	      self.expdate2 ||= date
	      self.expdate3 ||= date
	      self.expdate4 ||= date
	      self.expdate5 ||= date
	      self.expdate6 ||= date
	      self.expdate7 ||= date

	      self.exphead1 ||= workplace
	      self.exphead2 ||= workplace
	      self.exphead3 ||= workplace
	      self.exphead4 ||= workplace
	      self.exphead5 ||= workplace
	      self.exphead6 ||= workplace
	      self.exphead7 ||= workplace

	      self.expsubhead1 ||= workplace_subheader
	      self.expsubhead2 ||= workplace_subheader
	      self.expsubhead3 ||= workplace_subheader
	      self.expsubhead4 ||= workplace_subheader
	      self.expsubhead5 ||= workplace_subheader
	      self.expsubhead6 ||= workplace_subheader
	      self.expsubhead7 ||= workplace_subheader

	      
	      self.referee2 ||= workplace_subheader
	      self.referee3 ||= workplace_subheader
	      self.referee4 ||= workplace_subheader
	      self.referee5 ||= workplace_subheader

	      self.school ||= "placeholder text"
	      self.school2 ||= "placeholder text"
	      self.school3 ||= "placeholder text"
	      self.school4 ||= workplace_subheader
	      self.school5 ||= workplace_subheader


	    end
  end

end
#class AddAttachmentImageToDetails < ActiveRecord::Migration[5.1] make sure that all your migrations contains the [5.1] 

app/controllers/details_controller.rb
class DetailsController < ApplicationController
	impressionist actions: [:show], unique: [:session_hash]
	# before_action :require_permission, only: [:edit, :destroy, :update]
	before_action :find_detail, only: [:show, :update, :edit, :destroy, :layout3, :layout1, :showprint] #only on the SUED
	protect_from_forgery with: :exception #this was to also facilitate the custom fields created
	before_action :authenticate_user!

	
	def index
		# @details = Detail.all.order('created_at DESC')
		
		@details = current_user.details.order('created_at DESC')


	end

	def new
		@detail = current_user.details.build
		# @recipe = current_user.recipes.build
	end

	def create
		@detail = current_user.details.build(details_params)
		if @detail.save
			redirect_to @detail, notice: "CV Successfully created proceed with Editing"
		else
			render 'new'
		end
	end

	def show

		if @detail.layout == 1
    		render action: "layout1" and return

    	
    	elsif @detail.layout == 3
    		render action: "layout3" and return 
    	end
  			respond_to do |format|
		    format.html
		    format.pdf do
	   			render  :pdf => "file.pdf", :template => 'details/show.pdf.erb',
	   			encoding: "UTF-8", 
	   			layout: 'application'  
	      end
	    end
	  # render pdf: "file_name_of_your_choice",
   #             template: "invoices/show.pdf.erb",
   #             locals: {:invoice => @invoice}
	end


	def showprint

		if @detail.layout == 1
    		render action: "printlayout1" and return
    	
    	elsif @detail.layout == 3
    		render action: "printlayout3" and return 

    	elsif @detail.layout == 0
    		render action: "printshow" and return

    	end
    end

	def layout3 #custom method created so as to be able to print the pdf version to the screen
		respond_to do |format|
		    format.html
		    format.pdf do
	   			render  :pdf => "file.pdf", :template => 'details/layout3.pdf.erb',
	   			encoding: "UTF-8", 
	   			layout: 'application'  
	   		end
	   	end
	end

	def layout1 #custom method created so as to be able to generate the pdf version to the screen
		respond_to do |format| #the wicked gem only works this way
		    format.html
		    format.pdf do
	   			render  :pdf => "file.pdf", :template => 'details/layout1.pdf.erb',
	   			encoding: "UTF-8", 
	   			layout: 'application'  
	   		end
	   	end
	end


	def edit
	end

	def update
		if @detail.update(details_params)
			redirect_to @detail
		else
			render "edit" #renders the edit form
		end
	end

	def destroy
		@detail.destroy
		redirect_to root_path notice: "Successfully deleted"
	end


	private

	def require_permission
	  if current_user != Detail.find(params[:id]).user
	    redirect_to root_path, notice: "You cannot Edit or Delete resume created by You"
	    #Or do something else here
	  end
	end

	def details_params
		params.require(:detail).permit(:header, :subheader, :email, :telephone, :sex, :address, :githublink, :age, :twitter, :facebook,
			:objectives, :experience, :experience2, :experience3, :experience4, :interest, :language, :experience5, :keyskill, :education, 
			:image, :hobby, :referee, :project, :otherskill, :layout, :publish, :expdate1, :expdate2, :expdate3, :expdate4, :expdate5, 
			:expdate6, :expdate7, :exphead1, :exphead2, :exphead3, :exphead4, :exphead5, :exphead6, :exphead7, :expsubhead1, :expsubhead2,
			:expsubhead3, :expsubhead4, :expsubhead5, :expsubhead6, :expsubhead7, :experience6, :experience7, :techskill1, :techskill2, 
			:techskill3, :techskill4, :techskill5, :techskill6, :techskill7, :techskill8, :techskill9, :techskill10, :techskill11, :techskill12,
			:techskill13, :techskill14, :techskill15, :techskill16, :techskill17, :techskill18,	:techskill19, :techskill20, :techskill21, 
			:techskill22, :techskill23, :techskill24, :techskill25, :techskill26, :skill01, :skill02, :skill03, :skill04, :skill05, :skill06, :skill07, :skill08,
			:label1, :label2, :label3, :label4, :label5, :label6, :label7, :label8, :education2, :education3, :education4, :education5, :education6, :education7,
			:referee2, :referee3, :referee4, :referee5, :school, :school2, :school3, :school4, :school5, :school6, :school7)
	end 

	def find_detail
		@detail = Detail.find(params[:id])
	end


   

end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_footers.html.erb
<center>
 <%= link_to "Get PDF", detail_path(format: :pdf), class: "btn btn-danger btn-xs" %>
<%= link_to "PrintView", showprint_detail_path, class: "btn btn-primary btn-xs" %>
<% if current_user.id == @detail.user.id %> <%# if it is the user that created the recipe display the edit button %>
                <%= link_to "back", root_path, class: "btn btn-primary btn-xs" %>
                
                <%= link_to "delete", detail_path, method: :delete, data: {confirm: "Are You sure"}, class: "btn btn-danger btn-xs" %>  
<% end %>
</center>

app/views/details/edit.html.erb
<center><h2> Select Your Desired CV Concept</h2></center>
<%= render "form" %>

app/views/details/index.html.erb
<%#n we need to add each_slice, so that it can have multiple columns%>

<div class="row">
<div class="jumbotron">
	<center>
    <h2 class="title1"> Welcome to my resume</h2>
    <p>	<%=link_to "Create New Resume", new_detail_path, class:"btn btn-primary" %> </p>
    <p>click to Edit your already created resume</p>
    
              
    </center>
  </div>
  <style type="text/css">
  	.jumbotron {
  		background: linear-gradient(to right, rgba(255,0,0,0), rgba(26,205,1));
  		margin-top: 0px;  
  		font-family: verdana;
  	}
  	.title1 {
  		color: white;
  		font-weight: bold;
  	}
  </style>

	<% @details.each do |detail| %>
		<div class="col-sm-6 col-md-3">
			<div class="thumbnail">

				<div class="image_wrapper">
					<%=link_to detail do %>
					<p><%= detail.layout %> </p>
					<% if detail.layout == 0 %>
						<img id="layout2" src="https://image.ibb.co/d4Vy2G/layout.png" alt="Layout0" style="width:100%">
					<% elsif detail.layout == 1 %>
						<img id="layout1" src="https://image.ibb.co/iaLy2G/layout4.png" alt="Layout1" style="width:100%">
					<% elsif detail.layout == 2 %>
						<img id="layout3" src="https://image.ibb.co/bVNp9w/layout6.jpg" alt="Layout3" style="width:100%">
					<% elsif detail.layout == 3 %>
						<img id="layout4" src="https://image.ibb.co/kNvsUw/layout2.jpg" alt="Layout4" style="width:100%">
					<% elsif detail.layout == 4 %>
						<img id="layout5" src="https://image.ibb.co/ghkCwb/layout5.jpg" alt="Layout5" style="width:100%">	
					<% elsif detail.layout == 5 %>					
						<img id="layout6" src="https://image.ibb.co/gWCHwb/layout1.jpg" alt="Layout6" style="width:100%">
					<% end %>
				<h2><%= detail.header %></h2>
					<% end %>
					
				</div>
				
			</div>
			
		</div>
<% end %>
</div>


<script type="text/javascript">
	
</script>

app/views/details/layout1.html.erb
<!DOCTYPE html>
<html lang="fr"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>layout</title>

<!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<style type="text/css">
	/**********
/* Grille - 960.gs
**********/
.container_16 {
	max-width: 960px;
	width: 92%;
	margin: 0 auto;
}
.grid_6,
.grid_8,
.grid_10,
.grid_16 {
	display:inline;
	float: left;
	position: relative;
	margin-left: 1%;
	margin-right: 1%;
}

.container_16 .grid_6 {
	width:35.5%;
}

.container_16 .grid_8 {
	width:48.0%;
}

.container_16 .grid_10 {
	width:60.5%;
}

.container_16 .grid_16 {
	width:98.0%;
}

.clearfix:after {
	clear: both;
	content: ' ';
	display: block;
	font-size: 0;
	line-height: 0;
	visibility: hidden;
	width: 0;
	height: 0;
}

.clearfix {
	display: inline-block;
}

* html .clearfix {
	height: 1%;
}

.clearfix {
	display: block;
}



/**********
/* Header
**********/
	header[role=banner] {
		background:#fff;
		border-bottom:4px solid #33a4c9;
		padding: 6px 0;
		overflow: hidden;
	}
	
	
	
	header figure img {
		border-radius: 75px;
		height: 150px;
		position: relative;
		width: 150px;
	}
	
	header hgroup {
		float: left;
		padding: 20px 0;
	}
	
	header hgroup h1 {
		color:#555;
		font-family:'DroidSansBold', Arial, sans-serif;
	}
	
	header hgroup h2 {
		color:#cecece;
		font-style: italic;
		text-shadow: 1px 1px 0 rgba(0,0,0,.3);
	}

/************
/* Contact
************/
	::-webkit-input-placeholder  { color:#fff; }
	input:-moz-placeholder { color:#fff; }
	.placeholder { color: #fff; }

	.contactform {
		background-color: #33a4c9;
		color: #fff;
		display: none;
	}
	
	.contactform > div {
		padding: 21px 0;
	}
	
	.contactform input[type=text], .contactform input[type=email], .contactform textarea {
		background: #2983a0;
		border: 1px solid #226d85;
		border-radius: 2px;
		color: #fff;
		max-width: 100%;
		opacity: .7;
		padding: 10px 10px 9px 10px;
		margin-top: 0;
		position: relative;
		vertical-align: top;
		width: 100%;
	}
	
	.contactform input[type=text], .contactform input[type=email] {
		margin-bottom: 21px;
	}
	
	.contactform textarea {
		font-family: 'DroidSansRegular', Arial, sans-serif;
		font-size: 14px;
		height: 148px;
	}
	
	.contactform input[type=text]:focus, .contactform input[type=email]:focus, .contactform textarea:focus {
		border: 1px solid #226d85;
		opacity: 1;
		outline: none;
		-webkit-transition: opacity 1s;
	}
	
	.contactform input[type=submit] {
		background: #ff9f39;
		border: 1px solid #ff9f39;
		border-radius: 2px;
		color: #fff;
		cursor: pointer;
		font-weight: bold;
		font-size: 14px;
		margin: 0;
		padding: 10px 10px 9px 10px;
		width: 100%;
	}
	
	.contactform input.error, .contactform textarea.error {
		border: 1px solid red;
	}
	
	.contactform label.error {
		display: none !important;
	}

	/***********************
	/* Message du formulaire
	***********************/
		.messageform { 
			display: none; /* Affiché via jQuery */ 
			border-radius: 2px; 
			font-size: 14px;
			font-weight: bold;
			line-height: 17px;
			padding:10px 10px 9px 10px; 
			margin: 0;
			text-align: center;
			width: 100%; 
		}
		.envoi-valid, .envoi-error { 
			display: inline-block; 
		 }
		.envoi-valid { 
			background-color: #31D869;
			border:1px solid #108D3A; 
			color: #108D3A;
		}
		.envoi-error { 
			background-color: #FF5839;
			border:1px solid #A62913; 
			color: #A62913;
		}
		.envoi-error a {
			color: #A62913;
			text-decoration: underline;
		}
		

/***************
/* Corps - Main
***************/
	section[role=main] {
		padding: 21px 0;
		overflow: hidden;
	}
	
	section[role=main] > div {
		margin-top: 63px;
	}
	
	section[role=main] h3 {
		border-bottom: 1px solid #e1e1e1;
		padding: 0 0 20px 60px;
		margin-top: 0px;
		position: relative;
 	}
	
	section[role=main] h3:after, h3:before {
		content: ' ';
		display: block;
		height: 50px;
		left: 0;
		position: absolute;
		top: -15px;
		width: 50px;
	}
	
	section[role=main] h3:before {
		background-color: #33a4c9;
		border-radius: 25px;
	}
	
		/***************
		/* Pictos titres
		***************/
		
		section[role=main] h3:after {
			background:url('../img/pictos-titre.png') no-repeat 11px 10px;
		}
		
		section[role=main] .competences h3:after {
			background-position: 11px -34px;
		}
	
		section[role=main] .experiences h3:after {
			background-position: 11px -86px;
		}
		
		section[role=main] .formations h3:after {
			background-position: 10px -139px;
		}
		
		section[role=main] .loisirs h3:after {
			background-position: 10px -250px;
		}
		
		section[role=main] .contact h3:after {
			background-position: 11px -194px;
		}
	
	
	.experiences ul, .formations ul {
		margin-left: 60px;
	}
	
	section[role=main] h4 {
		margin-bottom: 0px;
	}
	
	section[role=main] h4 strong {
		color: #147393;
		font-weight: normal;
	}
	
	.experiences li, .formations li {
		margin-bottom: 63px;
	}
	
	.experiences li:last-child, .formations li:last-child {
		margin-bottom: 21px;
	}
	
	.experiences li p, .formations li p {
		margin-left: 30px;
	}
	
	/**********************************************
	/* Affichage des compétences sous forme de tags
	**********************************************/
	.competences .tags li {
		background-color:#33a4c9;
		border:1px solid #1b91b7;
		border-radius: 15px;
		color:#fff;
		display: inline-block;
		line-height: 13px;
		margin: 0 7px 17px 0;
		padding: 5px 10px;
	}
	
	/************************************************
	/* Affichage des compétences sous forme de barres
	*************************************************/
	.competences .barres li {
		margin-bottom: 21px;
		position: relative;
	}
	
	.competences .barres li:after {
		background: #e1e1e1;
		bottom: -4px;
		content: ' ';
		display: block;
		height: 5px;
		position: absolute;
		width:100%;
	}
	
	.competences .barres li span {
		background: #33a4c9;
		bottom: -4px;
		content: ' ';
		display: block;
		height: 5px;
		left: 0;
		position: absolute;
		width: inherit;
		z-index: 1;
	}
	
	
	/***********
	/* Pictos
	***********/
	.lieu, .dates, .phone, .mail, .site, .form, .twitter, .facebook, .dribbble, .skype {
		background: url('../img/pictos-gris.png') no-repeat;
		padding-left: 25px;
		margin: 0 10px 1px 10px;
	}
	
	.lieu {
		background-position: 0 -2px;
		color: #999;
	}
	
	.dates {
		background-position: 0 -22px;
		color: #999;
	}
	
	.phone {
		background-position: 0 -40px;
	}
	
	.mail {
		background-position: 0 -58px;
	}
	
	.site {
		background-position: 0 -80px;
	}
	
	.form {
		background-position: 0 -100px;
	}
	
	.twitter {
		background-position: 0 -122px;
	}
	
	.facebook {
		background-position: 0 -140px;
	}
	
	.dribbble {
		background-position: 0 -160px;
	}
	
	.skype {
		background-position: 0 -180px;
	}
</style>
<!--[if lt IE 9]> 
	<link rel="stylesheet" href="css/cv.css" media="screen">
<![endif]-->

</head>

<body>
<p id="clicker">click the number value to edit the font-size: &nbsp;<u><%= best_in_place @detail, :techskill23 %></u>
 <button type="button" class="btn btn-primary btn-xs" id="something">see changes</button></p>


<script>
$('#something').click(function() {
  
    window.location.href=window.location.href;
});
</script>


	<!-- Header -->
	<header role="banner">
		<div class="container_16">
				<hgroup>
					<h1><%= best_in_place @detail, :header %></h1>
                    <h2><%= best_in_place @detail, :subheader %></h2>
				</hgroup>

				
		</div>
	</header>
	
	
	
	<!-- Corps -->
	<section role="main" class="container_16 clearfix">
		<div class="grid_16">
			<!-- A propos -->
			<div class="grid_8 apropos">
				<h3><%= best_in_place @detail, :label1 %></h3>
				<p><%= best_in_place @detail, :skill08 %></p>
				<p><%= best_in_place @detail, :objectives %> </p>
			</div>
			
			<!-- Compétences -->
			<div class="grid_8 competences">
				<h3><%= best_in_place @detail, :label2 %></h3>
				<ul class="barres">
					<li data-skills="80"><%= best_in_place @detail, :techskill1 %><span style="width: 80%;"></span></li>
					<li data-skills="80"><%= best_in_place @detail, :techskill2 %><span style="width: 80%;"></span></li>
					<li data-skills="75"><%= best_in_place @detail, :techskill3 %><span style="width: 75%;"></span></li>
					<li data-skills="90"><%= best_in_place @detail, :techskill4 %><span style="width: 90%;"></span></li>
					<li data-skills="95"><%= best_in_place @detail, :techskill5 %><span style="width: 95%;"></span></li>
					<li data-skills="90"><%= best_in_place @detail, :techskill6 %><span style="width: 90%;"></span></li>
					<li data-skills="95"><%= best_in_place @detail, :techskill7 %><span style="width: 95%;"></span></li>

				</ul>
			</div>
		</div>
		
			<!-- Expériences -->
			<div class="job last">
                               
             <div class="grid_16 experiences">
				<h3><%= best_in_place @detail, :label4 %></h3>
				<ul>
					<li>
						<!-- <h4><strong><%= best_in_place @detail, :exphead2 %></strong></h4> -->
						<span class="lieu"><%= best_in_place @detail, :expsubhead2 %></span>
						<span class="dates"><%= best_in_place @detail, :expdate2 %></span>
						<p><%= best_in_place @detail, :experience2 %></p>
					</li>
					<li>
						<!-- <h4><strong><%= best_in_place @detail, :exphead3 %></strong></h4> -->
						<span class="lieu"><%= best_in_place @detail, :expsubhead3 %></span>
						<span class="dates"><%= best_in_place @detail, :expdate3 %></span>
						<p><%= best_in_place @detail, :experience3 %></p>
					</li>
					<li>
						<!-- <h4><strong><%= best_in_place @detail, :exphead4 %></strong></h4> -->
						<span class="lieu"><%= best_in_place @detail, :expsubhead4 %></span>
						<span class="dates"><%= best_in_place @detail, :expdate4 %></span>
						<p><%= best_in_place @detail, :experience4 %></p>
					</li>
					<li>
						<!-- <h4><strong><%= best_in_place @detail, :exphead5 %></strong></h4> -->
						<span class="lieu"><%= best_in_place @detail, :expsubhead5 %></span>
						<span class="dates"><%= best_in_place @detail, :expdate5 %></span>
						<p><%= best_in_place @detail, :experience5 %></p>
					</li>
				</ul>
			</div>
		
			<!-- Formations -->
		
			<div class="grid_16 formations">
				<h3><%= best_in_place @detail, :label7 %></h3>
				<ul>
				<br>
					
					<li>
						
						
						<p><%= best_in_place @detail, :education3 %></p>
					</li>
					<li>
						
						
						<p><%= best_in_place @detail, :education4 %></p>
					</li>
				</ul>
			</div>
		
			<!-- Loisirs -->
			<div class="grid_8 loisirs">
				<h3><%= best_in_place @detail, :label6 %></h3>
				<p><strong>Interests:</strong> <%= best_in_place @detail, :interest %> </p>
				<p><strong>Languages:</strong> <%= best_in_place @detail, :language %></p>
				<p><strong>Hobbies:</strong> <%= best_in_place @detail, :hobby %></p>
			</div>
		
			<!-- Contact -->
			<div class="grid_8 contact">
				<h3>Contact</h3>
			
				<ul>
					<li class="lieu"><i class="fa fa-phone"></i>&nbsp;<%= best_in_place @detail, :telephone %></li>
					<li class="phone"><i class="fa fa-home"></i>&nbsp;<%= best_in_place @detail, :address %></li>
					<li class="mail"><i class="fa fa-envelope"></i> &nbsp;<%= best_in_place @detail, :email %></li>
					<li class="site"><i class="fa fa-github"></i>&nbsp;<%= best_in_place @detail, :githublink %></li>
					<li class="form"><i class="fa fa-twitter"></i>&nbsp;<%= best_in_place @detail, :twitter %></li>
                    <li class="form"><i class="fa fa-facebook"></i>&nbsp;<%= best_in_place @detail, :facebook %></li>
				</ul>
			</div>
			
	<div class="grid_8 apropos">
	<br>
	<br>
				<h3><%= best_in_place @detail, :label5 %></h3>
				
				<li><%= best_in_place @detail, :referee2 %> </li>
				<li><%= best_in_place @detail, :referee3 %> </li>
				<li><%= best_in_place @detail, :referee4 %> </li>			

			</div>
		
			
	</section>


<script type="text/javascript">
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
        $('.first2').hide();
        var number = <%= @detail.techskill23 %>;
        var number2 = number + 'px';
        var originalSize = $('div').css('font-size', number2);
        // var customSize = $('div').css('font-size', 20);
        // $("#holder").text(customSize);
  // reset
      
      
           $(".resetMe").click(function(){
          $('div').css('font-size', number2); 

    });

    $('.last1').focusin(function(){
        $('.first2').show();
    });
   
     $(".increase").click(function(){
      var currentSize = $('div').css('font-size');
      var currentSize = parseFloat(currentSize)*1.2;
      $('div').css('font-size', currentSize);
      $("#holder").text(currentSize);
      return false;
       });
     $(".decrease").click(function(){

  var currentFontSize = $('div').css('font-size');
  var currentSize = $('div').css('font-size');
  var currentSize = parseFloat(currentSize)*0.8;
  $('div').css('font-size', currentSize);
   $("#holder").text(currentSize);

  return false;
   });
});
</script>
</body>
<center>


</center>
<center>
<br>
<br>
<%= link_to "PrintView", showprint_detail_path %>
<% if current_user.id == @detail.user.id %> <%# if it is the user that created the recipe display the edit button %>
                <%= link_to "back", root_path, class: "btn btn-default" %>
                <%= link_to "edit", edit_detail_path, class: "btn btn-default" %>
                <%= link_to "delete", detail_path, method: :delete, data: {confirm: "Are You sure"}, class: "btn btn-danger" %>  
<% end %>
<footer>
<p><small> designed by Onipe Theoderic Ohinoyi, tel: 07039148866, 2017</small>&copy; </p>
</footer> 
</center>
</html>

app/views/details/new.html.erb
<center><h2> Click to Select Your Desired CV Concept</h2></center>
<%= render 'form' %>

<br>